class DriveScopeMissing(Exception):
    ...

class ServiceAccountMissing(Exception):
    ...

class ConfigSettingsMissing(Exception):
    ...

class EmptyFolderError(Exception):
    ...

class EnglishTitleMissing(Exception):
    ...

